export const periods = [
  {
    number: 1,
    name: 'Tonight',
    startTime: '2021-02-06T21:00:00-05:00',
    endTime: '2021-02-07T06:00:00-05:00',
    isDaytime: false,
    temperature: 4,
    temperatureUnit: 'F',
    temperatureTrend: 'rising',
    windSpeed: '8 to 13 mph',
    windDirection: 'NNW',
    icon:
      'https://api.weather.gov/icons/land/night/snow,80/snow,70?size=medium',
    shortForecast: 'Light Snow',
    detailedForecast:
      'Snow between 10pm and 3am. Mostly cloudy. Low around 4, with temperatures rising to around 9 overnight. Wind chill values as low as -7. North northwest wind 8 to 13 mph, with gusts as high as 18 mph. Chance of precipitation is 80%. New snow accumulation of around one inch possible.',
  },
  {
    number: 2,
    name: 'Sunday',
    startTime: '2021-02-07T06:00:00-05:00',
    endTime: '2021-02-07T18:00:00-05:00',
    isDaytime: true,
    temperature: 16,
    temperatureUnit: 'F',
    temperatureTrend: 'falling',
    windSpeed: '5 to 12 mph',
    windDirection: 'NNW',
    icon: 'https://api.weather.gov/icons/land/day/sct/snow?size=medium',
    shortForecast: 'Mostly Sunny then Chance Snow Showers',
    detailedForecast:
      'A chance of snow showers after 4pm. Mostly sunny. High near 16, with temperatures falling to around 14 in the afternoon. Wind chill values as low as -9. North northwest wind 5 to 12 mph, with gusts as high as 18 mph. New snow accumulation of less than half an inch possible.',
  },
  {
    number: 3,
    name: 'Sunday Night',
    startTime: '2021-02-07T18:00:00-05:00',
    endTime: '2021-02-08T06:00:00-05:00',
    isDaytime: false,
    temperature: 10,
    temperatureUnit: 'F',
    temperatureTrend: 'rising',
    windSpeed: '6 mph',
    windDirection: 'NE',
    icon: 'https://api.weather.gov/icons/land/night/snow,20?size=medium',
    shortForecast: 'Chance Snow Showers then Slight Chance Light Snow',
    detailedForecast:
      'A chance of snow showers before 7pm, then a slight chance of snow. Mostly cloudy. Low around 10, with temperatures rising to around 12 overnight. Northeast wind around 6 mph. Chance of precipitation is 20%.',
  },
  {
    number: 4,
    name: 'Monday',
    startTime: '2021-02-08T06:00:00-05:00',
    endTime: '2021-02-08T18:00:00-05:00',
    isDaytime: true,
    temperature: 28,
    temperatureUnit: 'F',
    temperatureTrend: null,
    windSpeed: '8 mph',
    windDirection: 'E',
    icon: 'https://api.weather.gov/icons/land/day/snow,20/snow,30?size=medium',
    shortForecast: 'Chance Light Snow',
    detailedForecast:
      'A chance of snow. Mostly cloudy, with a high near 28. East wind around 8 mph. Chance of precipitation is 30%. New snow accumulation of less than half an inch possible.',
  },
  {
    number: 5,
    name: 'Monday Night',
    startTime: '2021-02-08T18:00:00-05:00',
    endTime: '2021-02-09T06:00:00-05:00',
    isDaytime: false,
    temperature: 18,
    temperatureUnit: 'F',
    temperatureTrend: null,
    windSpeed: '7 mph',
    windDirection: 'NE',
    icon: 'https://api.weather.gov/icons/land/night/snow,50?size=medium',
    shortForecast: 'Chance Light Snow',
    detailedForecast:
      'A chance of snow. Cloudy, with a low around 18. Northeast wind around 7 mph. Chance of precipitation is 50%. New snow accumulation of less than one inch possible.',
  },
  {
    number: 6,
    name: 'Tuesday',
    startTime: '2021-02-09T06:00:00-05:00',
    endTime: '2021-02-09T18:00:00-05:00',
    isDaytime: true,
    temperature: 25,
    temperatureUnit: 'F',
    temperatureTrend: null,
    windSpeed: '7 to 10 mph',
    windDirection: 'N',
    icon: 'https://api.weather.gov/icons/land/day/snow,20/bkn?size=medium',
    shortForecast: 'Slight Chance Light Snow then Mostly Cloudy',
    detailedForecast:
      'A slight chance of snow before 7am. Mostly cloudy, with a high near 25. Chance of precipitation is 20%.',
  },
  {
    number: 7,
    name: 'Tuesday Night',
    startTime: '2021-02-09T18:00:00-05:00',
    endTime: '2021-02-10T06:00:00-05:00',
    isDaytime: false,
    temperature: 13,
    temperatureUnit: 'F',
    temperatureTrend: null,
    windSpeed: '9 mph',
    windDirection: 'NNE',
    icon: 'https://api.weather.gov/icons/land/night/cold?size=medium',
    shortForecast: 'Mostly Cloudy',
    detailedForecast: 'Mostly cloudy, with a low around 13.',
  },
  {
    number: 8,
    name: 'Wednesday',
    startTime: '2021-02-10T06:00:00-05:00',
    endTime: '2021-02-10T18:00:00-05:00',
    isDaytime: true,
    temperature: 22,
    temperatureUnit: 'F',
    temperatureTrend: null,
    windSpeed: '12 mph',
    windDirection: 'NE',
    icon: 'https://api.weather.gov/icons/land/day/snow,20/snow,30?size=medium',
    shortForecast: 'Chance Light Snow',
    detailedForecast:
      'A chance of snow after 7am. Cloudy, with a high near 22. Chance of precipitation is 30%.',
  },
  {
    number: 9,
    name: 'Wednesday Night',
    startTime: '2021-02-10T18:00:00-05:00',
    endTime: '2021-02-11T06:00:00-05:00',
    isDaytime: false,
    temperature: 15,
    temperatureUnit: 'F',
    temperatureTrend: null,
    windSpeed: '10 mph',
    windDirection: 'NE',
    icon: 'https://api.weather.gov/icons/land/night/snow,30?size=medium',
    shortForecast: 'Chance Light Snow',
    detailedForecast:
      'A chance of snow. Cloudy, with a low around 15. Chance of precipitation is 30%.',
  },
  {
    number: 10,
    name: 'Thursday',
    startTime: '2021-02-11T06:00:00-05:00',
    endTime: '2021-02-11T18:00:00-05:00',
    isDaytime: true,
    temperature: 24,
    temperatureUnit: 'F',
    temperatureTrend: null,
    windSpeed: '12 mph',
    windDirection: 'NNE',
    icon: 'https://api.weather.gov/icons/land/day/snow,30/snow,20?size=medium',
    shortForecast: 'Chance Light Snow',
    detailedForecast:
      'A chance of snow. Mostly cloudy, with a high near 24. Chance of precipitation is 30%.',
  },
  {
    number: 11,
    name: 'Thursday Night',
    startTime: '2021-02-11T18:00:00-05:00',
    endTime: '2021-02-12T06:00:00-05:00',
    isDaytime: false,
    temperature: 11,
    temperatureUnit: 'F',
    temperatureTrend: null,
    windSpeed: '10 mph',
    windDirection: 'N',
    icon: 'https://api.weather.gov/icons/land/night/snow,20?size=medium',
    shortForecast: 'Slight Chance Light Snow',
    detailedForecast:
      'A slight chance of snow before 1am. Mostly cloudy, with a low around 11. Chance of precipitation is 20%.',
  },
  {
    number: 12,
    name: 'Friday',
    startTime: '2021-02-12T06:00:00-05:00',
    endTime: '2021-02-12T18:00:00-05:00',
    isDaytime: true,
    temperature: 18,
    temperatureUnit: 'F',
    temperatureTrend: null,
    windSpeed: '12 mph',
    windDirection: 'NW',
    icon: 'https://api.weather.gov/icons/land/day/bkn?size=medium',
    shortForecast: 'Mostly Cloudy',
    detailedForecast: 'Mostly cloudy, with a high near 18.',
  },
  {
    number: 13,
    name: 'Friday Night',
    startTime: '2021-02-12T18:00:00-05:00',
    endTime: '2021-02-13T06:00:00-05:00',
    isDaytime: false,
    temperature: 0,
    temperatureUnit: 'F',
    temperatureTrend: null,
    windSpeed: '12 mph',
    windDirection: 'NW',
    icon: 'https://api.weather.gov/icons/land/night/cold?size=medium',
    shortForecast: 'Mostly Cloudy',
    detailedForecast: 'Mostly cloudy, with a low around 0.',
  },
  {
    number: 14,
    name: 'Saturday',
    startTime: '2021-02-13T06:00:00-05:00',
    endTime: '2021-02-13T18:00:00-05:00',
    isDaytime: true,
    temperature: 10,
    temperatureUnit: 'F',
    temperatureTrend: null,
    windSpeed: '9 to 14 mph',
    windDirection: 'WNW',
    icon: 'https://api.weather.gov/icons/land/day/cold?size=medium',
    shortForecast: 'Partly Sunny',
    detailedForecast: 'Partly sunny, with a high near 10.',
  },
]
